//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaZakupow
{
    using System;
    using System.Collections.Generic;
    
    public partial class DostepnePotrawy
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public float Cena { get; set; }
    }
}
