//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaZakupow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ListaZakupowEntities : DbContext
    {
        public ListaZakupowEntities()
            : base("name=ListaZakupowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DostepnePotrawy> DostepnePotrawy { get; set; }
        public virtual DbSet<Listy> Listy { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
